spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      enabled: true
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/foo
    username:
    password:
    dirver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug


