INSERT INTO BOARD(BOARD_ID, TITLE, CONTENTS, WRITER, HIT, CREATED_BY, UPDATED_BY) VALUES(1, '제목1','내용1','글쓴이1',0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO BOARD(BOARD_ID, TITLE, CONTENTS, WRITER, HIT, CREATED_BY, UPDATED_BY) VALUES(2, '제목1','내용1','글쓴이1',0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO MEMBER(MEMBER_ID, EMAIL, PASSWORD, NAME, AUTH) VALUES(1,'wlsgmdchemd@naver.com', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'ROLE_USER')


